spring:
  datasource:
    url: jdbc:mysql://localhost:3306/digital_banking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update       # automatically creates/updates tables
    show-sql: true           # prints SQL queries to console
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
